name: Deploy to Streamlit Cloud

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download NLTK data
      run: |
        python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords'); nltk.download('punkt_tab')"
    
    - name: Test imports
      run: |
        python -c "
        import sys, os
        sys.path.append('src')
        from data_preprocessing import DataPreprocessor
        from ml_models import FakeNewsClassifier
        from advanced_analysis import TextAnalyzer
        print('✅ All imports successful!')
        "
    
    - name: Create deployment info
      run: |
        echo "Deployment successful at $(date)" > deployment_info.txt
        echo "Commit: ${{ github.sha }}" >> deployment_info.txt
        echo "Branch: ${{ github.ref_name }}" >> deployment_info.txt
